# Generated by Django 3.1.1 on 2020-12-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmchapter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastachievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('eventdate', models.DateTimeField(blank=True, null=True)),
                ('eventparticipants', models.IntegerField()),
                ('eventwinners', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='past',
            name='event',
            field=models.CharField(max_length=100),
        ),
    ]
