# Generated by Django 3.1.1 on 2020-12-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acmchapter', '0004_upcomming_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomming',
            name='img',
        ),
    ]
