# Generated by Django 3.1.1 on 2021-01-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmchapter', '0006_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomming',
            name='img',
            field=models.ImageField(blank=True, upload_to='acmchapter/'),
        ),
    ]
