# Generated by Django 3.2.7 on 2021-11-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmchapter', '0007_upcomming_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='past',
            name='speaker',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
